version: '3'

networks:
  url-shortener:
    driver: bridge

services:
  url-shortener-db:
    image: postgres:16.1-alpine
    container_name: url-shortener-db-dev
    volumes:
      - postgresql-volume-shortener:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=url-shortener
      - POSTGRES_USER=shortener
      - POSTGRES_PASSWORD=Pa55wOrd
    ports:
      - "5432:5432"

volumes:
  postgresql-volume-shortener:
